language: python
python:
- '3.6'
branches:
  only:
  - master
  - develop
services:
- postgresql
env:
- DJANGO=2.0 DB=postgres
global:
- PGPORT=5432
before_install:
- sudo apt update
- sudo apt install chromium-chromedriver
- cd decide
install:
- pip install selenium
- pip install codacy-coverage
- pip install -r ../requirements.txt
before_script:
- cp local_settings.travis.py local_settings.py
- cd decide
- cp -f travis_settings.py settings.py
- cd ..
- psql -U postgres -c "create user decide password 'decide'"
- psql -U postgres -c "create database test_decide owner decide"
- psql -U postgres -c "ALTER USER decide CREATEDB"
- python manage.py makemigrations
- python manage.py migrate
script:
- coverage run --branch --source=. ./manage.py test voting --keepdb
- coverage xml
- python-codacy-coverage -r coverage.xml
addons:
  postgresql: '9.6'
  chrome: stable
deploy:
  - provider: heroku
    app: decide-egc-tinto-votaciones
    strategy: git
    on:
      branch: master
    api_key:
      secure: fWNOjQTVMA2GnYw1tdnYCyP1BKHfjH2Fy1mR6bZUU+BWx5LFnmPIBbp7S33Vy3K5cdp6BqDuuaIX0s/hWoOA/k6yBLjlcPGHJX5lHth57lVRzK3P4jlFsl56yAAxrEAFbZvaU7r36fR6tNvhE/bsHDGPTFisAOtbRKJClKnq7gTFHJ/RPu8dk4EF1FVIgPep2elD0/KKajeyaLEucxZZOkIy7kILHxxJP8MFZB+4IzBjAVvVwR9udLCNdz6eEg1tp7KdVdp1bbPuTLJ5eBUNvmOrTFgmdG9+ZkoPcpxwcTzaemE5cZwtGlIATwQyex+V0J9Zf0aHfwhx0MyXc3/hgrzaZrX6pty2oVTp8wfX2Z1LaAIVhxTcwQb+RPXKshAFcxCYHaKTIZGsGXR4cN5ozB9amT07rJuKqYHLOL8zHaXUHj88UY74oi3CK5cpmUsDVQMY4MVvax1HSBXXX5hn95reyl86LFvIVHbXhDTGsNvsNMnMAVGdSQMNXd+DAzgRmsZsUiSvxVwytom4dQoS9HFapLkQI8Q/4vHjj/JxXFrDddwmQ9gC2qy+aqhA+QWQVIkez6bWkJzThwBXUwsain3a+hNA/cSkUr0wu8Atx8RI7wyOoNqDZm5YiOqbUQVrfqsmamJz0yekJqWe1bCKv6WeFx2ZXElemwlu4yEliK4=
  
  - provider: heroku
    app: decide-egc-tinto-votaciones-dv
    strategy: git
    on:
      branch: develop
    api_key:
      secure: fWNOjQTVMA2GnYw1tdnYCyP1BKHfjH2Fy1mR6bZUU+BWx5LFnmPIBbp7S33Vy3K5cdp6BqDuuaIX0s/hWoOA/k6yBLjlcPGHJX5lHth57lVRzK3P4jlFsl56yAAxrEAFbZvaU7r36fR6tNvhE/bsHDGPTFisAOtbRKJClKnq7gTFHJ/RPu8dk4EF1FVIgPep2elD0/KKajeyaLEucxZZOkIy7kILHxxJP8MFZB+4IzBjAVvVwR9udLCNdz6eEg1tp7KdVdp1bbPuTLJ5eBUNvmOrTFgmdG9+ZkoPcpxwcTzaemE5cZwtGlIATwQyex+V0J9Zf0aHfwhx0MyXc3/hgrzaZrX6pty2oVTp8wfX2Z1LaAIVhxTcwQb+RPXKshAFcxCYHaKTIZGsGXR4cN5ozB9amT07rJuKqYHLOL8zHaXUHj88UY74oi3CK5cpmUsDVQMY4MVvax1HSBXXX5hn95reyl86LFvIVHbXhDTGsNvsNMnMAVGdSQMNXd+DAzgRmsZsUiSvxVwytom4dQoS9HFapLkQI8Q/4vHjj/JxXFrDddwmQ9gC2qy+aqhA+QWQVIkez6bWkJzThwBXUwsain3a+hNA/cSkUr0wu8Atx8RI7wyOoNqDZm5YiOqbUQVrfqsmamJz0yekJqWe1bCKv6WeFx2ZXElemwlu4yEliK4=
