# Generated by Django 2.0 on 2021-01-05 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_auto_20210101_1813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voting',
            name='question',
        ),
        migrations.AddField(
            model_name='voting',
            name='question',
            field=models.ManyToManyField(related_name='voting', to='voting.Question'),
        ),
    ]
