# Generated by Django 2.0 on 2021-01-06 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0006_auto_20210105_1319'),
        ('voting', '0007_auto_20210106_1529'),
    ]

    operations = [
    ]
