# Generated by Django 2.0 on 2021-01-07 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0008_merge_20210106_1611'),
        ('voting', '0009_auto_20210106_2332'),
    ]

    operations = [
    ]
